BUTTONS: dict[str, str] = {'8_bit':'8-Bit',
                           'acid':'Acid',
                           'ambient':'Ambient',
                           'breaks':'Breaks',
                           'disco':'Disco',
                           'downtempo':'Downtempo',
                           'Drum_Bass':'Drum & Bass',
                           'dub':'Dub',
                           'electro':'Electro',
                           'experimental':'Experimental',
                           'funk':'Funk',
                           'hardcore':'Hardcore',
                           'hip_hop_rap':'Hip-hop/Rap',
                           'house':'House',
                           'industrial':'Industrial',
                           'instrumental':'Instrumental',
                           'jazz':'Jazz',
                           'moombahton':'Moombahton',
                           'pop':'Pop',
                           'reggae':'Reggae',
                           'rock':'Rock',
                           'soul':'Soul',
                           'synth_pop':'Synth-Pop',
                           'techno':'Techno',
                           'trance':'Trance',
                           'uk_garage':'UK Garage',}

AMBIENT_BUTTONS = {'ambient_dub':'Ambient Dub',
                   'berlin_school':'Berlin School',
                   'chillout':'Chillout',
                   'dark_ambient':'Dark Ambient',
                   'illbient':'Illbient',
                   'new_age':'New Age',
                   'psybient':'Psybient',}